# https://github.com/atom/ci/blob/master/README.md

language: objective-c
node_js:
  - v4

env:
  - APM_TEST_PACKAGES="linter"

script: 'npm run ci'

notifications:
  email:
    on_success: never
    on_failure: change
